---
- name: control node set-up
  hosts: contolnode
  become: true
  tasks:
  - name: install epel
    yum:
      name: epel-release
      state: present
  - name: install ansible
    yum:
      name: ansible
      state: present
  - name: set hostname
    hostname:
      name: controlnode.example.com
  - file:
      path: /home/vagrant/working_dir
      state: directory
      mode: 0755
  - name: change selinux context to avoid errors
    selinux:
      policy: targeted
      state: permissive
  - name: generate ssh keys
    openssh_keypair:
      path: "~/.ssh/id_rsa"
      type: rsa
      size: 4096
      state: present
      force: no
