---
- name: managed node set-up
  hosts: managednode
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: set hostname
    hostname:
      name: managednode.example.com
  - name: disable selinux
    selinux:
      state: disabled
