---
- name: managed node set-up
  hosts: managednode
  become: true
  tasks:
  - name: set hostname
    hostname:
      name: managednode.example.com
  - name: disable selinux
    selinux:
      state: disabled
