Vagrant.configure('2') do |config|
  config.vm.provision 'shell', inline: 'echo Hello'

  config.vm.define 'contolnode' do |controlnode|
    config.vm.box = "centos/7"
    controlnode.vm.provision 'ansible' do |ansible|
      ansible.playbook = 'control.yml'
    end
  end

  config.vm.define 'managednode' do |managednode|
    config.vm.box = "centos/7"
    managednode.vm.provision 'ansible' do |ansible|
      ansible.playbook = 'managed.yml'
    end
  end
end
